### ISSUE TITLE
Issue from Devoxx workshop

### ISSUE THREAD

**Issue by d-sauer** [alvarosanchez/micronaut-workshop-java#1]
Hi, during the Devoxx workshop on exercise #2, an existing solution I got following error.

`➜  clubs git:(master) ✗ pwd
/Users/davorsauer/development/repo/github/micronaut-workshop-java/ex02/solution/clubs
➜  clubs git:(master) ✗ ll
total 56
drwxr-xr-x  11 davorsauer  staff   352 Nov 12 15:11 .
drwxr-xr-x   3 davorsauer  staff    96 Nov 12 13:53 ..
-rw-r--r--   1 davorsauer  staff   101 Nov 12 13:53 .gitignore
drwxr-xr-x   5 davorsauer  staff   160 Nov 12 15:09 .gradle
-rw-r--r--   1 davorsauer  staff   129 Nov 12 13:53 Dockerfile
-rw-r--r--   1 davorsauer  staff  1734 Nov 12 13:53 build.gradle
drwxr-xr-x   3 davorsauer  staff    96 Nov 12 13:53 gradle
-rwxr-xr-x   1 davorsauer  staff  5296 Nov 12 13:53 gradlew
-rwxr-xr-x   1 davorsauer  staff  2176 Nov 12 13:53 gradlew.bat
-rw-r--r--   1 davorsauer  staff    84 Nov 12 13:53 micronaut-cli.yml
drwxr-xr-x   4 davorsauer  staff   128 Nov 12 13:53 src
➜  clubs git:(master) ✗ code .
➜  clubs git:(master) ✗ gradle clean

BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
➜  clubs git:(master) ✗ gradle test

> Task :compileJava
Note: Creating bean classes for 4 type elements

> Task :compileTestJava
Note: Creating bean classes for 2 type elements

> Task :test

clubs.ClubRepositoryImplTest STANDARD_OUT
    15:12:26.739 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
    15:12:28.089 [Test worker] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.3.6.Final}
    15:12:28.091 [Test worker] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
    15:12:28.262 [Test worker] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.13.Final
    15:12:28.276 [Test worker] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
    15:12:28.479 [Test worker] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
    15:12:28.794 [Test worker] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
    Hibernate: create table Club (id bigint not null, name varchar(255) not null, stadium varchar(255), primary key (id))
    Hibernate: create sequence hibernate_sequence start with 1 increment by 1

clubs.ClubRepositoryImplTest > testCrudOperations() STANDARD_OUT
    15:12:30.470 [nioEventLoopGroup-1-3] ERROR i.m.d.registration.AutoRegistration - Error occurred during service registration with Consul: Connect Error: Connection refused: localhost/127.0.0.1:8500
    io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: localhost/127.0.0.1:8500
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$23(DefaultHttpClient.java:1025)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
    Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
    15:12:30.560 [Test worker] INFO  o.s.o.h.HibernateTransactionManager - Using DataSource [org.apache.tomcat.jdbc.pool.DataSource@2bb13ad9{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.h2.Driver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=false; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE; username=sa; validationQuery=SELECT 1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=3000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; useStatementFacade=true; }] of Hibernate SessionFactory for HibernateTransactionManager
    15:12:30.570 [nioEventLoopGroup-1-3] ERROR i.m.d.registration.AutoRegistration - Error occurred de-registering service [clubs] with Consul: Connect Error: Connection refused: localhost/127.0.0.1:8500
    io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: localhost/127.0.0.1:8500
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$23(DefaultHttpClient.java:1025)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
    Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted

clubs.ClubRepositoryImplTest > testCrudOperations() FAILED
    org.springframework.transaction.CannotCreateTransactionException
        Caused by: java.lang.IllegalStateException

clubs.ClubControllerTest STANDARD_OUT
    15:12:30.795 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
    15:12:30.941 [Test worker] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
    15:12:30.971 [Test worker] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
    Hibernate: create table Club (id bigint not null, name varchar(255) not null, stadium varchar(255), primary key (id))
    Hibernate: create sequence hibernate_sequence start with 1 increment by 1

clubs.ClubControllerTest > testFindAllClubs() STANDARD_OUT
    15:12:31.191 [Test worker] INFO  o.s.o.h.HibernateTransactionManager - Using DataSource [org.apache.tomcat.jdbc.pool.DataSource@31a0b0c4{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.h2.Driver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=false; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE; username=sa; validationQuery=SELECT 1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=3000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; useStatementFacade=true; }] of Hibernate SessionFactory for HibernateTransactionManager
    15:12:31.219 [nioEventLoopGroup-3-3] ERROR i.m.d.registration.AutoRegistration - Error occurred during service registration with Consul: Connect Error: Connection refused: localhost/127.0.0.1:8500
    io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: localhost/127.0.0.1:8500
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$23(DefaultHttpClient.java:1025)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
    Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
    15:12:31.234 [nioEventLoopGroup-3-3] ERROR i.m.d.registration.AutoRegistration - Error occurred de-registering service [clubs] with Consul: Connect Error: Connection refused: localhost/127.0.0.1:8500
    io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: localhost/127.0.0.1:8500
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$23(DefaultHttpClient.java:1025)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
    Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted

clubs.ClubControllerTest > testFindAllClubs() FAILED
    org.springframework.transaction.CannotCreateTransactionException
        Caused by: org.hibernate.service.UnknownServiceException

clubs.ClubControllerTest > testGetOneClub() FAILED
    org.springframework.transaction.CannotCreateTransactionException
        Caused by: java.lang.IllegalStateException

3 tests completed, 3 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/davorsauer/development/repo/github/micronaut-workshop-java/ex02/solution/clubs/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
4 actionable tasks: 4 executed
➜  clubs git:(master) ✗ gradle -version

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Mac OS X 10.14.1 x86_64`

Test results and stack:
[test-results.tar.gz](https://github.com/alvarosanchez/micronaut-workshop-java/files/2572221/test-results.tar.gz)

**Comment by alvarosanchez** [comment]
It is complaining that it can't connect to `localhost:8500`, and that is because you didn't start the Consul container as it was explained in the docs. Start the container and give it another go.
